name: Build Hermes on GitHub releases

on:
  release:
    types: [published]

jobs:
  # Build Hermes for iOS
  build_hermes_ios:
    name: Build Hermes for iOS (release)
    runs-on: macos-latest
    env:
      HERMES_WS_DIR: ${{ github.workspace }}
    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: jwlawson/actions-setup-cmake@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4

      # Prepare cache
      - name: Get Hermes commit ID
        id: hermes-commit-id
        run: |
          echo "HERMES_COMMIT_ID=$(git rev-parse HEAD:hermes)" >> $GITHUB_OUTPUT
      - name: Restore Hermes build cache
        uses: actions/cache@v4
        if: always()
        with:
          key: ${{ runner.os }}-ios-cache-${{ env.HERMES_COMMIT_ID }}
          path: |
            ./build
            hermes/build_appletvos
            hermes/build_appletvsimulator
            hermes/build_catalyst
            hermes/build_host_hermesc
            hermes/build_iphoneos
            hermes/build_iphonesimulator
            hermes/build_xros
            hermes/build_xrsimulator
            hermes/destroot
          restore-keys: |
            ${{ runner.os }}-ios-cache

      # Build
      - name: Build Hermes (+compiler) for host
        run: |
          cmake -S hermes -B build -G Ninja
          cmake --build ./build
      - name: Build Hermes iOS Framework
        run: |
          cd hermes
          ./utils/build-ios-framework.sh

      - name: Log outputs
        run: ls -laR hermes/destroot

      # Upload
      - name: Prepare folders for zip
        run: |
          mkdir tmp_zip_workspace
          cp -r hermes/destroot/include tmp_zip_workspace/include
          cp -r hermes/destroot/Library/Frameworks/* tmp_zip_workspace
      - name: Zip the .xcframework + include Headers
        run: |
          cd tmp_zip_workspace
          zip -r ../Hermes-Apple.zip *

      - name: Upload Hermes to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Hermes-Apple.zip
          asset_name: "Hermes-Apple.zip"
          asset_content_type: application/zip

  # Build Hermes for Android
  build_hermes_android:
    name: Build Hermes for Android (release)
    runs-on: ubuntu-22.04
    env:
      HERMES_WS_DIR: ${{ github.workspace }}
    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install dependencies
        run: |-
          sudo apt update
          sudo apt install -y git openssh-client cmake build-essential \
              libreadline-dev libicu-dev zip python3 ninja-build

      # Prepare cache
      - name: Get Hermes commit ID
        run: |
          echo "HERMES_COMMIT_ID=$(git rev-parse HEAD:hermes)" >> $GITHUB_OUTPUT
      - name: Restore Hermes build cache
        uses: actions/cache@v4
        if: always()
        with:
          path: |
            build
            build_android
            hermes/build_host_hermesc
          key: ${{ runner.os }}-android-cache-${{ env.HERMES_COMMIT_ID }}
          restore-keys: |
            ${{ runner.os }}-android-cache

      # Build
      - name: Build Hermes (+compiler) for host
        run: |
          cmake -S hermes -B build -G Ninja
          cmake --build ./build --target hermesc -j 4
      - name: Build Hermes Android framework
        run: |
          cd hermes/android
          ./gradlew githubRelease --build-cache

      - name: Log outputs
        run: ls -laR build_android

      - name: Zip the .aar and .so files
        run: |
          cd build_android/outputs
          zip -r ../../Hermes-Android.zip *

      - name: Upload Hermes aar to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Hermes-Android.zip
          asset_name: "Hermes-Android.zip"
          asset_content_type: application/zip

      # Gradle cache doesn't like daemons
      - name: Stop Gradle Daemon
        run: cd ./hermes/android && ./gradlew --stop
