name: Build Hermes and upload to GitHub releases

on:
  push:
    branches: [main]

jobs:
  # Build Hermes for iOS
  build_hermes_ios:
    name: Build Hermes for iOS (release)
    runs-on: macos-latest
    env:
      HERMES_WS_DIR: ${{ github.workspace }}
    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: jwlawson/actions-setup-cmake@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4

      # Prepare cache
      - name: Restore CMake build cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-build-ios-cache
          path: |
            build
            hermes/build_appletvos
            hermes/build_appletvsimulator
            hermes/build_catalyst
            hermes/build_host_hermesc
            hermes/build_iphoneos
            hermes/build_iphonesimulator
            hermes/build_xros
            hermes/build_xrsimulator
            hermes/destroot

      # Build
      - name: Build Hermes (+compiler) for host
        run: |
          cmake -S hermes -B build -G Ninja
          cmake --build ./build
      - name: Build Hermes iOS Framework
        run: |
          cd hermes
          ./utils/build-ios-framework.sh

      - name: Log outputs
        run: ls -laR hermes/destroot

      # Upload
      - name: Prepare folders for zip
        run: |
          mkdir tmp_zip_workspace
          cp -r hermes/destroot/include tmp_zip_workspace/include
          cp -r hermes/destroot/Library/Frameworks/* tmp_zip_workspace
      - name: Zip the .xcframework + include Headers
        run: |
          cd tmp_zip_workspace
          zip -r ../Hermes-Apple.zip *

      - name: Upload Hermes-Apple.zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hermes-Apple.zip
          path: Hermes-Apple.zip

      - name: Zip Hermes itself
        run: |
          cd build/bin
          zip ../hermes-debug.zip hermes
      - name: Upload Hermes Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hermes-debug-macos.zip
          path: hermes-debug.zip

  # Build Hermes for Android
  build_hermes_android:
    name: Build Hermes for Android (release)
    runs-on: ubuntu-22.04
    env:
      HERMES_WS_DIR: ${{ github.workspace }}
    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install dependencies
        run: |-
          sudo apt update
          sudo apt install -y git openssh-client cmake build-essential \
              libreadline-dev libicu-dev zip python3 ninja-build

      # Prepare cache
      - name: Restore CMake build cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-buildcache
          path: |
            build
            build_android
            hermes/build_host_hermesc

      # Build
      - name: Build Hermes (+compiler) for host
        run: |
          cmake -S hermes -B build -G Ninja
          cmake --build ./build --target hermesc -j 4
      - name: Build Hermes Android framework
        run: |
          cd hermes/android
          ./gradlew githubRelease --build-cache

      - name: Log outputs
        run: ls -laR build_android

      - name: Zip the .aar and .so files
        run: |
          cd build_android/outputs
          zip -r ../../Hermes-Android.zip *

      - name: Upload Hermes-Android.zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hermes-Android.zip
          path: Hermes-Android.zip

      - name: Zip Hermes itself
        run: |
          cd build/bin
          zip ../hermes-debug.zip hermes
      - name: Upload Hermes Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hermes-debug-linux.zip
          path: hermes-debug.zip

      # Gradle cache doesn't like daemons
      - name: Stop Gradle Daemon
        run: cd ./hermes/android && ./gradlew --stop

  create_github_release:
    name: Create GitHub Release with both Artifacts
    needs: [build_hermes_ios, build_hermes_android]
    runs-on: ubuntu-latest
    steps:
      - name: Download Hermes-Apple.zip
        uses: actions/download-artifact@v4
        with:
          name: Hermes-Apple.zip

      - name: Download Hermes-Android.zip
        uses: actions/download-artifact@v4
        with:
          name: Hermes-Android.zip

      - name: Download hermes-debug-macos.zip
        uses: actions/download-artifact@v4
        with:
          name: hermes-debug-macos.zip

      - name: Download hermes-debug-linux.zip
        uses: actions/download-artifact@v4
        with:
          name: hermes-debug-linux.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Hermes-Apple.zip
            Hermes-Android.zip
            hermes-debug-macos.zip
            hermes-debug-linux.zip
